
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model Post
 * 
 */
export type Post = Prisma.PostModel
/**
 * Model Schedule
 * 
 */
export type Schedule = Prisma.ScheduleModel
/**
 * Model Resource
 * 
 */
export type Resource = Prisma.ResourceModel
/**
 * Model Study
 * 
 */
export type Study = Prisma.StudyModel
/**
 * Model Chapter
 * 
 */
export type Chapter = Prisma.ChapterModel
/**
 * Model Verse
 * 
 */
export type Verse = Prisma.VerseModel
/**
 * Model Selection
 * 
 */
export type Selection = Prisma.SelectionModel
/**
 * Model Guide
 * 
 */
export type Guide = Prisma.GuideModel
/**
 * Model GuideStep
 * 
 */
export type GuideStep = Prisma.GuideStepModel
/**
 * Model Session
 * 
 */
export type Session = Prisma.SessionModel
/**
 * Model SessionStep
 * 
 */
export type SessionStep = Prisma.SessionStepModel
