
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma. Through it you get access to all the models, enums, and input types.
 * If you're looking for something you can import in the client-side of your application, please refer to the `browser.ts` file instead.
 * 
 * 🟢 You can import this file directly.
 */

import * as process from 'node:process'
import * as path from 'node:path'
import { fileURLToPath } from 'node:url'
globalThis['__dirname'] = path.dirname(fileURLToPath(import.meta.url))

import * as runtime from "@prisma/client/runtime/library"
import * as $Enums from "./enums"
import * as $Class from "./internal/class"
import * as Prisma from "./internal/prismaNamespace"

export * as $Enums from './enums'
export * from "./enums"
/**
 * ## Prisma Client
 * 
 * Type-safe database client for TypeScript
 * @example
 * ```
 * const prisma = new PrismaClient()
 * // Fetch zero or more Posts
 * const posts = await prisma.post.findMany()
 * ```
 * 
 * Read more in our [docs](https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client).
 */
export const PrismaClient = $Class.getPrismaClientClass(__dirname)
export type PrismaClient<LogOpts extends Prisma.LogLevel = never, OmitOpts extends Prisma.PrismaClientOptions["omit"] = Prisma.PrismaClientOptions["omit"], ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = $Class.PrismaClient<LogOpts, OmitOpts, ExtArgs>
export { Prisma }


// file annotations for bundling tools to include these files
path.join(__dirname, "libquery_engine-darwin.dylib.node")
path.join(process.cwd(), ".prisma/client/libquery_engine-darwin.dylib.node")

/**
 * Model Post
 * 
 */
export type Post = Prisma.PostModel
/**
 * Model Schedule
 * 
 */
export type Schedule = Prisma.ScheduleModel
/**
 * Model Resource
 * 
 */
export type Resource = Prisma.ResourceModel
/**
 * Model Study
 * 
 */
export type Study = Prisma.StudyModel
/**
 * Model Chapter
 * 
 */
export type Chapter = Prisma.ChapterModel
/**
 * Model Verse
 * 
 */
export type Verse = Prisma.VerseModel
/**
 * Model Selection
 * 
 */
export type Selection = Prisma.SelectionModel
/**
 * Model Guide
 * 
 */
export type Guide = Prisma.GuideModel
/**
 * Model GuideStep
 * 
 */
export type GuideStep = Prisma.GuideStepModel
/**
 * Model Session
 * 
 */
export type Session = Prisma.SessionModel
/**
 * Model SessionStep
 * 
 */
export type SessionStep = Prisma.SessionStepModel
